### ISSUE TITLE
Migration to the repovizz organization

### ISSUE THREAD

**Issue by lemonzi** [chaosct/pd-repovizz#1]
We have a repovizz organization for storing repovizz-related opensource tools (where the Python Qualysis exporter will go eventually). 

If you want, we can move this there once it's working so that it has more visibility.

(unless it's a "personal" project, but since you added Panos I assumed it's an "official" library for the MHD)

**Comment by chaosct** [comment]
This is for a UPF workshop in physiological computing. But whenever we got everything working we can talk about making it official if appropriate.

**Comment by lemonzi** [comment]
Ok, good :)

BTW, I have a couple of PD libraries out there, they may be of help:

https://github.com/lemonzi/autoSync (automatic two-way data binding for GUI elements and data)
https://github.com/lemonzi/3pD (3D algebra, originally tested with kinect - skeletonOSC)
